#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(

    # Application title
    titlePanel("Histograms of commonly used distributions"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            radioButtons("dist", "Distribution type:",
                         c("Normal" = "norm",
                           "Uniform" = "unif",
                           "Log-normal" = "lnorm",
                           "Exponential" = "exp")),
            sliderInput("npoints",
                        "Number of points:",
                        min = 1000,max = 10000, value = 1000, step = 1000)
        ),
        # Show a plot of the generated distribution
        mainPanel(
            textOutput("outText"),
            tags$head(tags$style("#outText{color: green;
                                 font-size: 20px;font-style: bold;}")),
            plotOutput("distPlot"),
            br(),
            h4('Instructions'),
            helpText("This application is for plotting the histograms of commonly 
            used distributions. This is especially useful for students who learn 
            about these distributions. This app plots following distributions:"),
            HTML("<ul>
                 <li>Normal</li>
                 <li>Uniform</li>
                 <li>Log-normal</li>
                 <li>Exponential</li>
                 </ul>"),
            h4('How to use?'),
            HTML("<ul>
                  <li>Select the distribution from <b>Distribution type</b> radio
                  buttons. The histogram of selected distribution will be displayed. And 
                  the density curve is overlayed on top of the histogram.</li>
                  <li><b>Number of points</b> slider allows to choose the number 
                  of points to be simulated for the selected distribution. You can 
                  select values between 1000 and 10000. The slider increments in
                  steps of 1000.</li>
                  </ul>
                 <b><i>Note:By default the Normal distribuition is selected. And the histogram is
                  generated by simulating 500 random normal points.</i></b>
                  <br>
                 ")
            
        )
    )
))
